openapi: '3.0.1'
info: 
  version: 25.02.06
  title: Mywebsite API
  description: | 
    As a REST API, Mywebsite accepts and returns JSON payloads, along with the associated `application/json` content type.

    You can learn everything you need to know about authentication, credentials, data formats, and more in the [API Basics](/guide/api-basics/environments.html) section.
    
    Like the rest of the documentation, this reference focuses on the latest version of the Mywebsite API (Connect).
  contact: 
    name: Mywebsite
    url: https://mywebsite.com
servers:
  - url: https://baseURL.co     
    #description: Dummy URL for content optimization in API Reference
  - url: https://your-company-name.sandbox.mywebsite.co
    description: Sandbox environment
  - url: https://your-company-name.api.mywebsite.com
    description: Production environment
paths:
  /core-connect/account-details/{walletId}/raw:
    get:
      tags:
        - Account Details
      summary: Get JSON Account Details
      description: | 
        Retrieve the necessary data (JSON) to generate the Account Details of a given Wallet.

        This endpoint requires per-session [SCA](/guide/strong-customer-authentication/introduction.html).
      operationId: getRawWalletAccountDetail
      security:
        - jwt:
            - read_only
            - read_write
  /core-connect/account-details/{walletId}/computed:
    get:
      tags:
        - Account Details
      summary: Get PDF Account Details
      description: | 
        Retrieve a Wallet RIB and IBAN in PDF format.

        This endpoint requires per-session [SCA](/guide/strong-customer-authentication/introduction.html).
      operationId: getComputedWalletAccountDetail
      security:
        - jwt:
          - read_only
          - read_write
  /oauth/token:
    post:
      tags:
        - Authentication
      summary: Obtain Access Token
      operationId: postAuth
      description: |
        Exchange authorization codes or refresh tokens for access tokens.
        The response will include the access token and optionally a refresh token, along with their expiration details.
      security: []
  /core-connect/balances/{walletId}:
    get:
      tags:
          - Balances
      summary: Get Wallet Balance history
      description: Retrieve the Balance History of a Wallet.
      operationId: getWalletBalanceHistory
      security:
        - jwt:
            - read_only
  /core-connect/cardtransactions:
    get:
      tags:
        - Card Transactions
      summary: Get all Card Transactions
      operationId: getCoCardTransactions
      description: Retrieve all the Card Transactions. This is the preferred request for a dashboard-oriented approach. You shouldn't expose this endpoint to your end users.
      security:
        - jwt: []
  /core-connect/cardtransactions/{cardId}:
    get:
      tags:
        - Card Transactions
      summary: Get Card Transactions
      operationId: getCoCardTransaction
      description: Retrieve the Card Transactions for a specific card. This request is preferred for a dashboard-oriented usage. You shouldn't expose this endpoint to your end users.
      security:
        - jwt: []
  /core-connect/support-user:
    get:
      tags:
        - Support Users
      summary: Get all Support Users
      description: Retrieve all the Support Users.
      operationId: getAllSupportUser
      security:
        - jwt:
            - support_user_management
            # verified scope
    post:
      tags:
        - Support Users
      summary: Create Support User
      description: Create a new Support User.
      operationId: createSupportUser
      security:
        - jwt:
            - support_user_management
            # verified scope
  /core-connect/support-user/{supportUserId}:
    get:
      tags:
        - Support Users
      summary: Get Support User
      description: Retrieve a Support User based on its `id`.
      operationId: findOneSupportUserById
      security:
        - jwt:
            - support_user_management
            # verified scope
    put:
      tags:
        - Support Users
      summary: Update Support User
      description: Modify a Support User information.
      operationId: updateSupportUser
      security:
        - jwt:
            - support_user_management
            # verified scope
    delete:
      tags:
        - Support Users
      summary: Delete Support User
      description: Delete a Support User
      operationId: deleteSupportUser
      security:
        - jwt:
            - support_user_management
            # verified scope
  /core-connect/support-user/{supportUserId}/unblock:
    put:
      tags:
        - Support Users
      summary: Unblock Support User
      description: Unblock a Support User. Support Users may be blocked if they failed to login 3 times in a row.
      operationId: unblockSupportUser
      security:
        - jwt:
            - support_user_management
            # verified scope
  /core-connect/mid/metadata:
    get:
      tags:
        - Merchant ID Metadata
      summary: Get all MID metadata
      description: Retrieve all MID metadata.
      operationId: getAllMidMetadata
      security:
        - jwt:
            - admin
            # verified scope
    put:
      tags:
        - Merchant ID Metadata
      summary: Put Bulk metadata
      description: Create or update bulk metadata
      operationId: putMidMetadata
      security:
        - jwt:
            - admin
            # verified scope
  /core-connect/mid/{mid}/metadata:
    put:
      tags:
        - Merchant ID Metadata
      summary: Store MID Metadata
      description: Store metadata for a Merchant Id.
      operationId: postMidMetadata
      security:
        - jwt:
            - admin
            # verified scope
    get:
      tags:
        - Merchant ID Metadata
      summary: Get MID Metadata
      description: Retrieve metadata for a Merchant Id.
      operationId: getMidMetadata
      security:
        - jwt:
            - admin
  /core-connect/payouts/{payoutId}/proof:
    get:
      tags:
        - Payouts
      summary: Create Payout Proof
      description: | 
        Generate and download a proof of payout in .PDF format. See [Proof of Payout](/guide/transfers/proof-of-payout.html) for more information.
      operationId: getProofPayout
      security:
        - jwt:
          - read_only
          - read_write
  /core-connect/card/bulk/{id}/report:
    get:
      tags:
        - Cards Bulk Creation
      summary: Get Report
      description: Get a link to download the bulk creation report.
      operationId: getCardBulkReport
      security:
        - jwt:
          - admin
          # verified scope
  /core-connect/card/bulk:
    post:
      tags:
        - Cards Bulk Creation
      summary: Create Bulk Card Order
      description: | 
        Create a Bulk Card order to create multiple cards at once.

        This endpoint requires per-session [SCA](/guide/strong-customer-authentication/introduction.html).
      operationId: postBulkCard
      security:
        - jwt:
          - admin
          # verified scope
    get:
      tags:
        - Cards Bulk Creation
      summary: Get Bulk Card Order
      description: Search bulk card orders.
      operationId: getBulkCard
      security:
        - jwt:
          - admin
          # verified scope
  /core-connect/operations/{walletId}/report:
    get:
      tags:
        - Operations
      summary: Get Operations Report
      description: Retrieve an Operations Report based on the corresponding Wallet `id`.
      operationId: getOperationsReport
      security:
        - jwt:
          - read_only
          - read_write
    post:
      tags:
        - Operations
      security:
        - jwt:
          - read_only
          - read_write
      summary: Create Operations Report
      description: Create a CSV export that includes all operations for a given Wallet on a given period.
      operationId: postOperationsReport
  /core-connect/merchantIdRestrictionGroups/{groupId}/mid/metadata:
    get:
      tags:
        - Merchant ID Metadata
      summary: Get all MID with metadata
      description: Retrieve all Merchant Ids with metadata. 
      operationId: getAllMidMetadataBYyGroup
      security:
        - jwt:
            - read_write
  /customization/templates:
    get: 
      tags:
        - API Templates
      summary: Get Available Templates
      description: Retrieve the list of templates.
      operationId: getTemplates
  /customization/templates/{templateName}:
    get:
      tags:
        - API Templates
      summary: Get Template Variables
      description: Retrieve the list of variables for the given template
      operationId: getTemplateVariables
      security:
        - jwt:
            - admin
    delete:
      tags:
        - API Templates
      summary: Delete Template
      description: Delete a Template.
      operationId: deleteTemplate
      security:
        - jwt:
            - admin
  /customization/templates/{templateName}/template:
    get:
      tags:
        - API Templates
      summary: Get Template
      description: Retrieve the currently configured template.
      operationId: getTemplate
      security:
        - jwt:
            - admin
    put:
      tags:
        - API Templates
      summary: Upload Template
      description: Upload a replacement for an existing Template.
      operationId: putTemplateUpload
      security:
        - jwt:
            - admin
  /customization/templates/{templateName}/example:
    get:
      tags:
        - API Templates
      summary: Build Template Example
      description: Test your template by building one with dummy values.
      operationId: getTemplateExample
      security:
        - jwt:
            - admin
  /core-connect/users/{userId}/kyc/document:
    get:
      tags:
        - User Document Pre-review
      summary: Search Pre-review Documents 
      description: Retrieve all pre-review documents for given user
      operationId: getKYCDocuments
      security:
        - jwt:
            - read_write
    post:
      tags:
        - User Document Pre-review
      summary: Create Upload Document Form
      description: Generate a pre-signed form to upload documents for pre-review.
      operationId: getPreSignedKycForm
      security:
        - jwt:
            - read_write
  /core-connect/kyc/documents/{documentId}/status:
    put:
      tags:
        - User Document Pre-review
      summary: Pre-review Document
      description: Update the pre-review status and comment of the document.
      operationId: updateDocument
      security:
        - jwt:
            - admin
  /core-connect/kyc/documents/{documentId}:
    delete:
      tags:
        - User Document Pre-review
      summary: Delete Pre-review Document 
      description: Delete a pre-review document.
      operationId: deleteKYCDocumentcument
      security:
        - jwt:
            - admin
  /core-connect/kyc/documents/need-review:
    get:
      tags:
        - User Document Pre-review
      summary: Search Documents to pre-review
      description: | 
        Retrieve all pre-review documents to review. This endpoint is for [Onboarded Users](/api-reference/api-endpoints.html#tag/User%20Onboarding) only.
      operationId: getKYCDocumentsToReview
      security:
        - jwt:
            - admin
  /core-connect/kyc/documents/{documentId}/preview:
    get:
      tags:
        - User Document Pre-review
      summary: Get Download URL
      description: Retrieve the pre-signed URL to download the pre-review document.
      operationId: getPresignedUrlDocument
      security:
        - jwt:
            - read_only
  # /core-connect/mass-payouts/import:
  #   post:
  #     tags:
  #       - Mass Payouts
  #     summary: Import SEPA.xml File
  #     description: Import a SEPA.xml file for mass payout
  #     operationId: postMassPayoutImport
  #     requestBody:
  #       content:
  #         multipart/form-data:
  #           schema:
  #             type: object
  #             properties:
  #               file:
  #                 type: string
  #                 format: binary
  #                 nullable: false
  #               reference:
  #                 type: string
  #                 nullable: false
  #     responses:
  #       '201':
  #         description: CREATED
  #         content:
  #           application/json:
  #             schema:
  #               type: object
  #               properties:
  #                 importId:
  #                   type: string
  #                 status:
  #                   type: string
  #       '400':
  #         $ref: '#/components/responses/BadRequestError'
  #       default:
  #         $ref: '#/components/responses/DefaultError'
  #     security:
  #       - jwt:
  #           - read_write
  #           - read_only
  # /core-connect/mass-payouts/report/{reference}:
    # get:
    #   tags:
    #     - Mass Payouts
    #   summary: Get Mass Payout Report
    #   operationId: getMassPayoutReportRef
    #   description: |
    #     Check the progress of the process of creating the report file and allows you to retrieve it.
    #   parameters:
    #     - in: path
    #       name: reference
    #       schema:
    #         type: string
    #       required: true
    #       description: Unique reference of the `MassPayoutImport` object.
    #   responses:
    #     '200':
    #       description: OK
    #       content:
    #         application/json:
    #           schema:
    #             type: object
    #             properties:
    #               url:
    #                 type: string
    #                 nullable: false
    #               status:
    #                 type: string
    #                 nullable: false
    #               processed_creditors:
    #                 type: integer
    #                 nullable: false
    #               total_creditors:
    #                 type: integer
    #                 nullable: false
    #     default:
    #       $ref: '#/components/responses/DefaultError'
    #   security:
    #     - jwt:
    #         - read_write
    #         - read_only
  /core-connect/operations:
    get:
      tags:
        - Operations
      summary: Search Operations
      description: |
        Retrieve Operations that match your search conditions. The request must specify at least: `walletId`, `dateTo`, `dateFrom`.

        This endpoint requires per-session [SCA](/guide/strong-customer-authentication/introduction.html) for operations that are more than 90 days old.
      operationId: getOperations
      security:
        - jwt:
          - read_only
          - read_write
  /core-connect/sca/scawallets:
    get:
      tags:
        - SCA
      summary: Search SCA Wallets
      description: Retrieve the list of [SCA Wallets](/guide/strong-customer-authentication/introduction.html#sca-wallet-object) for a given user.
      operationId: getSCAWallets
      security:
        - jwt:
          - read_only
    post:
      tags:
        - SCA
      summary: Create SCA Wallet
      operationId: postScaWallet
      description: Create a new [SCA Wallet](/guide/strong-customer-authentication/introduction.html#sca-wallet-object) manually.
      security:
        - jwt: []
  /core-connect/sca/scawallets/swap:
    post:
      tags:
        - SCA
      summary: Swap SCA Wallets
      description: Create an SCA Wallet while deleting the previous one as users should have only one device enrolled.
      operationId: swapSCAWallets
      security:
        - jwt:
          - read_write
  /core-connect/sca/scawallets/{scaWalletId}:
    delete:
      tags:
        - SCA
      summary: Delete SCA Wallet
      operationId: deleteScaWallet
      description: Permanently delete an SCA Wallet.
      security:
        - jwt: []
    get:
      tags:
        - SCA
      summary: Get SCA Wallet
      description: Retrieve an SCA Wallet by providing its `id`.
      operationId: getScaWallet
      security:
        - jwt: []
  /core-connect/sca/scawallets/{scaWalletId}/lock:
    put:
      tags:
        - SCA
      summary: Lock SCA Wallet
      operationId: putScaWallet
      description: |
        Locks an SCA Wallet so that none of the services it offers can be unlocked until it is unlocked.
      security:
        - jwt: []
  /core-connect/sca/scawallets/{scaWalletId}/unlock:
    put:
      tags:
        - SCA
      summary: Unlock SCA Wallet
      description: Unlock an SCA Wallet.
      operationId: unlockScaWallet
      security:
        - jwt: []
  /core-connect/sca/scawallets/{scaWalletId}/resetPin:
    put:
      tags:
        - SCA
      summary: Reset PIN
      operationId: resetScaWalletPin
      description: |
        Reset the PIN code of an SCA Wallet if the user has locked their Wallet after too many consecutive wrong PIN attempts. See [Reset PIN (Mobile)](/guide/strong-customer-authentication/sca-wallet-lifecycle.html#reset-pin-mobile) for more information.
        
        Once the PIN reset, the Customer can set a new PIN via the mobile application.
      security:
        - jwt: []
  /core-connect/sca/setPasscode:
    put:
      summary: Change Passcode
      description: |
        Change the passcode ([Web Native SCA](/guide/strong-customer-authentication/introduction.html#web-native)).
      operationId: setPasscode
      tags:
        - SCA
      security:
        - jwt:
          - read_write
  /simulation/scaProof:
    post:
      tags: 
        - SCA Proof Simulation
      summary: Simulate SCA Proof
      description: | 
        Create an `scaProof` for testing SCA authentication flows without a dedicated frontend. Use the `scaProof` to secure end user flow with a `delegated_end_user` JWT in `sandbox`. 
        
        See the [Simulate SCA Proof](/guide/strong-customer-authentication/faking-operations.html#simulate-sca-proof) article for more information.
      operationId: postScaProof
      security:
        - jwt:
          - admin
  /core-connect/sca/externalOperations:
    post:
      summary: Create External Operation declaration
      description: Declare an SCA External Operation (i.e., a sensitive action that was made outside of Mywebsite services).
      operationId: postExtOperation
      tags:
        - SCA External Operations
      security:
        - jwt:
          - read_write
  /core-connect/sca/externalOperations/{externalOperationId}:
    put:
      summary: Update External Operation declaration
      description: | 
        Modify an SCA External Operation declaration. 
        
        This feature is only available for Per Operation operations, in other words for external operations whose action name is: `externalMassPayoutOrderCreation`, 
        `externalMassTransferOrderCreation`, `externalScheduledPayoutOrder`, or `externalScheduledTransferOrder`.
      operationId: putExtOperation
      tags:
        - SCA External Operations
      security:
        - jwt:
          - read_write
  /core-connect/statements/{walletId}/raw:
    get:
      tags:
          - Account Statements
      summary: Get JSON Account Statement
      description: | 
        Retrieve the raw data (json) to build a Wallet account statement.

        This endpoint requires per-session [SCA](/guide/strong-customer-authentication/introduction.html).
      operationId: getRawStatement
      security:
        - jwt: []
  /core-connect/statements/{walletId}/computed:
    get:
      tags:
          - Account Statements
      summary: Get PDF Account Statement
      description: | 
        Retrieve a Wallet account statement in pdf format.

        This endpoint requires per-session [SCA](/guide/strong-customer-authentication/introduction.html).
      operationId: getPdfAccountStatement
      security:
        - jwt: []
  /v1/balances:
    get:
      tags:
        - Balances
      summary: Search Balances
      description: Retrieve Balances for a given `walletId` or `userId`.
      operationId: getBalances
      security:
        - jwt: []
  /v1/beneficiaries:
    get:
      tags:
        - Beneficiaries
      summary: Search Beneficiaries
      description: Retrieve Beneficiary bank accounts that match search criteria.
      operationId: getBeneficiaries
      security:
        - jwt: []
    post:
      tags:
        - Beneficiaries
      summary: Create Beneficiary
      description: | 
        Create a new benefeciary bank account. This endpoint requires per-operation [SCA](/guide/strong-customer-authentication/introduction.html).
      operationId: postBeneficiary
      security:
        - jwt: []
  /v1/beneficiaries/{beneficiaryId}:
    get:
      tags:
        - Beneficiaries
      summary: Get Beneficiary
      description: Retrieve a Beneficiary bank account based on its `id`.
      operationId: getBeneficiary
      security:
        - jwt: []
    put:
      tags:
        - Beneficiaries
      summary: Update Beneficiary
      description: | 
        Modify a benefeciary bank account information.

        This endpoint requires per-operation [SCA](/guide/strong-customer-authentication/introduction.html).
      operationId: putBeneficiary
      security:
        - jwt: []
  /v1/businesssearchs:
    get:
      tags:
        - Businesses
      summary: Search Businesses
      operationId: searchBusiness
      description: |
        The search endpoint returns some business information.
      security:
        - jwt: []
  /v1/businessinformations:
    get:
      tags:
        - Businesses
      summary: Get Business Information
      operationId: getBusinessInfo
      description: |
        The get business information endpoint returns all already known business information. End user will have then to verify/correct it.
      security:
        - jwt: []
  /v1/cards:
    get:
      tags:
        - Cards
      summary: Search Cards
      description: Retrieve Cards based on search criteria.
      operationId: getCards
      security:
        - jwt: []
  /v1/cards/{cardId}:
    get:
      tags:
        - Cards
      summary: Get Card
      description: Retrieve a Card based on its `id`.
      operationId: getCard
      security:
        - jwt: []
    put:
      tags:
        - Cards
      summary: Update Card
      operationId: putCard
      description: |
        Update the restriction groups of the card, as well as the `cardTag`.
      security:
        - jwt: []
  /v1/cards/CreateVirtual:
    post:
      tags:
        - Cards
      summary: Create Virtual Card
      operationId: postCardVirtual
      description: |
        Create a new virtual card. To use a card, it must be activated (`/v1/cards/{cardId}/Activate`).

        This endpoint requires per-session [SCA](/guide/strong-customer-authentication/introduction.html).
      security:
        - jwt: []
  /v1/cards/RequestPhysical:
    post:
      tags:
        - Cards
      summary: Create Physical Card
      operationId: postCardPhysical
      description: |
        Create a new physical card. To use a card, it must be activated (`/cards/{id}/Activate`).

        This endpoint requires per-session [SCA](/guide/strong-customer-authentication/introduction.html).
      security:
        - jwt: []
  /v1/cards/Register3DS:
    post:
      tags:
        - Cards
      summary: Register 3D secure
      operationId: post3ds
      description: |
        Register a card to 3D secure service. The user's mobile number must begin with `+`, or `00`, and the country dialing code.
      security:
        - jwt: []
  /v1/cardimages:
    get:
      tags:
        - Cards
      summary: Get Card Image
      description: | 
        Retrieve a virtual card image.

        This endpoint requires per-operation [SCA](/guide/strong-customer-authentication/introduction.html).
      operationId: getCardImage
      security:
        - jwt: []
  /v1/cards/{cardId}/Activate:
    put:
      tags:
        - Cards
      summary: Activate Card
      operationId: activateCard
      description: |
        Activate the Card (updating the `isLive` attribute to `1`). A Card must be activated to be used.

        This endpoint requires per-operation [SCA](/guide/strong-customer-authentication/introduction.html).
      security:
        - jwt: []
  /v1/cards/{cardToken}/public-token-activation:
    put:
      tags:
        - Cards
      summary: Activate Card Public Token
      operationId: activateCardToken
      description: |
        Activate the Card (updating the `isLive` attribute to `1`). Ideal for end-user oriented action. A Card must be activated to be used.

        This endpoint requires per-operation [SCA](/guide/strong-customer-authentication/introduction.html).
      security:
        - jwt: []
  /v1/cards/{cardId}/Assign:
    put:
      tags:
        - Cards
      summary: Reassign Card
      operationId: reassignCard
      description: |
        Assign the Card to another User or Wallet.
      security:
        - jwt: []
  /v1/cards/{cardId}/AssignWallet:
    put:
      tags:
        - Cards
      summary: Assign Wallet
      operationId: assignCardWallet
      description: |
        Assign the Card to another Wallet.
      security:
        - jwt: []
  /v1/cards/{cardId}/ChangePIN:
    put:
      tags:
        - Cards
      summary: Change Card PIN
      operationId: changePin
      description: | 
        Change the Card PIN code knowing the current one.

        This endpoint requires per-operation [SCA](/guide/strong-customer-authentication/introduction.html).
      security:
        - jwt: []
  /v1/cards/{cardId}/ConvertVirtual:
    put:
      tags:
        - Cards
      summary: Convert virtual card to physical
      operationId: convertVirtual
      description: |
        Convert a virtual Card into a physical one. The converted card will be both virtual and physical.
      security:
        - jwt: []
  /v1/cards/{cardId}/Limits:
    put:
      tags:
        - Cards
      summary: Update Card Limits
      operationId: putLimits
      description: | 
        Modify the Card limits.

        This endpoint requires per-operation [SCA](/guide/strong-customer-authentication/introduction.html).
      security:
        - jwt: []
  /v1/cards/{cardId}/LockUnlock:
    put:
      tags:
        - Cards
      summary: Update Card Lock Status
      operationId: updateBlockStatus
      description: | 
        Block or unblock a card.

        This endpoint requires per-operation [SCA](/guide/strong-customer-authentication/introduction.html).
      security:
        - jwt: []
  /v1/cards/{cardId}/Options:
    put:
      tags:
        - Cards
      summary: Update Card Options
      description: | 
        Modify the Card permissions group.

        This endpoint requires per-operation [SCA](/guide/strong-customer-authentication/introduction.html).
      operationId: cardOptions
      security:
        - jwt: []
  /v1/cards/{cardId}/Regenerate:
    put:
      tags:
        - Cards
      summary: Regenerate Card
      operationId: regenerateCard
      description: |
        Recreate the card image if the card is unlocked. 
        
        Useful when changing card design, company name, or when retrieving the image results in a 404.
      security:
        - jwt: []
  /v1/cards/{cardId}/setPIN:
    put:
      tags:
        - Cards
      summary: Set Card PIN
      operationId: setPin
      description: | 
        Overwrite the Card PIN code.

        This endpoint requires per-operation [SCA](/guide/strong-customer-authentication/introduction.html).
      security:
        - jwt: []

  /v1/cards/{cardId}/UnblockPIN:
    put:
      tags:
        - Cards
      summary: Unblock Card PIN
      description: | 
        Unblock the Card PIN code.

        This endpoint requires per-operation [SCA](/guide/strong-customer-authentication/introduction.html).
      operationId: unblockPin
      security:
        - jwt: []
  /v1/cards/{cardId}/unblockcvc2:
    put:
      tags:
        - Cards
      summary: Unblock Card CVC2 
      operationId: unblockCvc
      description: |
        Unblock a Card whose CVC2 is locked.
      security:
        - jwt: []
  /v1/cards/{cardId}/authentication-methods:
    get:
      tags:
        - Card 3DSecure Enrollment (SCA)
      summary: Get Authenticaton Methods
      operationId: getAuthMethods
      description: | 
        Retrieve the authentication methods of a Card.
      security:
        - jwt: []
    post:
      tags:
        - Card 3DSecure Enrollment (SCA)
      summary: Create Authenticaton Methods
      operationId: postAuthMethods
      description: | 
        Define the authentication method of a Card.
      security:
        - jwt: []
  /v1/cards/{cardId}/authentication-methods/{methodId}:
    get:
      tags:
          - Card 3DSecure Enrollment (SCA)
      summary: Get Authentication Method
      description: Retrieve details regarding the authentication method of a Card
      operationId: getAuthMethodsDetails
      security:
        - jwt: []
    delete:
      tags:
        - Card 3DSecure Enrollment (SCA)
      summary: Delete Authentication Method
      description: Delete the authentication method of a Card. Only available for OOB method.
      operationId: deleteAuthMethods
      security:
        - jwt: []
  /v1/cards/{cardId}/renewalDetails:
    get:
      tags:
        - Cards
      summary: Get Renewal Details
      operationId: getRenewalDetails
      description: |
        Retrieve the Card `renewalType`.
      security:
        - jwt:
          - read_write
          - admin
          - legal
    put:
      tags:
        - Cards
      summary: Update Renewal Details
      operationId: updateRenewalDetails
      description: |
        Update the Card `renewalType`.
      security:
        - jwt:
          - read_write
          - admin
          - legal
  /v1/cards/{cardId}/renew:
    put:
      tags:
        - Cards
      summary: Renew Card
      operationId: putRenew
      description: |
        Renew a Card manually.
      security:
        - jwt:
          - read_write
          - admin
          - legal
  /v1/{cardId}/digitalizedCards:
    get:
      security:
        - jwt: []
      description: |
        Retrieve the list of digitalized cards for a given `cardId`.
      summary: Get Digitalized Cards
      operationId: getDigitalized
      tags: 
        - Digitalized Cards
  /v1/digitalizedCard/{id}:
    put:
      security:
        - jwt: []
      description: |
        Update the status of a payment Token.
      summary: Update Payment Token Status
      operationId: putDigitalized
      tags: 
        - Digitalized Cards
    delete:
      security:
        - jwt: []
      description: |
        Deactivate a payment Token.
      summary: Deactivate Payment Token
      operationId: deleteDigitalized
      tags: 
        - Digitalized Cards
    get:
      security:
        - jwt: []
      description: Retrieve a payment token.
      summary: Get Payment Token
      operationId: getPaymentToken
      tags: 
        - Digitalized Cards
  /v1/cardtransactions:
    get:
      tags:
        - Card Transactions
      summary: Search Card Transactions
      description: |
        Retrieve Card Transactions based at least on one of the following intputs: `cardId`, `paymentId`, `publicToken`, `walletId`. This is the preferred request for end-user-oriented usage.
      operationId: readCardTransaction
      security:
        - jwt: []
  /v1/cardtransactions/{cardtransactionId}:
    get:
      tags:
        - Card Transactions
      summary: Get Card Transaction
      description: Retrieve a Card Transaction based on its `id`.
      operationId: getCardtransaction
      security:
        - jwt: []
  /v1/countryRestrictionGroups:
    get:
      tags:
        - Country Restriction Groups
      summary: Search Country Restriction Groups
      description: Retrieve country restriction groups that match search criteria.
      operationId: getCountryRestrictionGroups
      security:
        - jwt: []
    post:
      tags:
        - Country Restriction Groups
      summary: Create Country Restriction Group
      description: Create a new country restriction group.
      operationId: postCountryRestrictionGroup
      security:
        - jwt: []
  /v1/countryRestrictionGroups/{id}:
    get:
      tags:
        - Country Restriction Groups
      summary: Get Country Restriction Group
      description: Retrive a Country Restriction Group based on its `id`.
      operationId: getCountryRestrictionGroupsId
      security:
        - jwt: []
    put:
      tags:
        - Country Restriction Groups
      summary: Update Country Restriction Group
      description: Edit a country restriction group.
      operationId: putCountryRestrictionGroups
      security:
        - jwt: []
    delete:
      tags:
        - Country Restriction Groups
      summary: Cancel Country Restriction Group
      description: Cancel a country restriction group.
      operationId: deleteCountryRestrictionGroups
      security:
        - jwt: []
  /v1/documents:
    get:
      tags:
        - User Documents
      summary: Search Documents
      description: Retrieve Documents based on search criteria.
      operationId: getDocuments
      security:
        - jwt:
          - read_only
    post:
      tags:
        - User Documents
      summary: Create Document
      description: Create a Document.
      operationId: createDocuments
      security:
        - jwt:
          - read_write
  /v1/documents/{documentId}:
    get:
      tags:
        - User Documents
      summary: Get Document
      description: Retrieve a Document using its `id`.
      operationId: getDocument
      security:
        - jwt:
          - read_only
    put:
      tags:
        - User Documents
      summary: Update Document
      description: Change the `name` of a Document.
      operationId: putDocument
      security:
        - jwt:
          - read_write
    delete:
      tags:
        - User Documents
      summary: Delete Document
      description: Remove a document.
      operationId: deleteDocument
      security:
        - jwt:
          - read_write
  /v1/documents/{documentId}/download:
    get:
      tags:
        - User Documents
      summary: Get Document Download URL
      description: | 
        Retrieve a Document download URL. You may read [the dedicated documentation for this feature](/guide/user-verification/documents.html#download-documents).
      operationId: getDocumentDownloadUrl
      security:
        - jwt:
          - read_only
  /v1/issuerInitiatedDigitizationDatas:
    post:
      tags:
        - Digitalized Cards
      summary: Request issuerInitiatedDigitizationData
      description: | 
        Create a new issuerInitiatedDigitizationData request

        This endpoint requires per-operation [SCA](/guide/strong-customer-authentication/introduction.html).
      operationId: tavRequestPOST
      security:
        - jwt: []
  /v1/mandates:
    get:
      tags:
        - Mandates
      summary: Search Mandates
      description: Retrieve Mandates that match search criteria.
      operationId: getMandates
      security:
        - jwt:
          - read_only
          - read_write
    post:
      tags:
        - Mandates
      summary: Create Mandate
      description: |
        Create a new mandate.
      operationId: postMandates
      security:
        - jwt:
          - read_write
  /v1/mandates/{mandateId}:
    get:
      tags:
        - Mandates
      summary: Get Mandate
      description: Retrieve a Mandate based on its `id`.
      operationId: getMandate
      security:
        - jwt:
          - read_only
          - read_write
    delete:
      tags:
        - Mandates
      summary: Revoke Mandate
      description: Change the Mandate status to `CANCELED`.
      operationId: deleteMandate
      security:
        - jwt:
          - read_write
  /v1/mccRestrictionGroups:
    get:
      tags:
        - MCC Restriction Groups
      summary: Search MCC Restriction Groups
      description: Retrieve MCC Restriction Groups that match search criteria.
      operationId: getMccRestrictionGroups
      security:
        - jwt:
          - read_only
          - read_write
    post:
      tags:
        - MCC Restriction Groups
      summary: Create MCC Restriction Group
      description: Create a new Merchant Category Code (MCC) restriction group.
      operationId: postMccRestrictionGroup
      security:
        - jwt:
          - read_write
  /v1/mccRestrictionGroups/{id}:
    get:
      tags:
        - MCC Restriction Groups
      summary: Get MCC Restriction Group
      description: Retrieve a MCC Group based on its `id`.
      operationId: getMccRestrictionGroupsId
      security:
        - jwt:
          - read_only
          - read_write
    put:
      tags:
        - MCC Restriction Groups
      summary: Update MCC Restriction Group
      description: Edit a MCC Restriction group.
      operationId: putMccRestrictionGroups
      security:
        - jwt:
          - read_write
    delete:
      tags:
        - MCC Restriction Groups
      summary: Cancel MCC Restriction Group
      description: Cancel a MCC restriction group.
      operationId: deleteMccRestrictionGroups
      security:
        - jwt:
          - read_write
  /v1/merchantIdRestrictionGroups:
    get:
      tags:
        - Merchant ID Restriction Groups
      summary: Search MID Restriction Groups
      description: Retrieve Merchant ID Restriction Groups that match search criteria.
      operationId: getMerchantIdRestrictionGroup
      security:
        - jwt:
          - read_only
          - read_write
    post:
      tags:
        - Merchant ID Restriction Groups
      summary: Create MID Restriction Group
      description: Create a new Merchant ID restriction group.
      operationId: postMerchantIdRestrictionGroup
      security:
        - jwt:
          - read_write
  /v1/merchantIdRestrictionGroup/{id}:
    put:
      tags:
        - Merchant ID Restriction Groups
      summary: (DEPRECATED) Update MID Restriction Group
      description: Deprecated
      operationId: putMerchantIdRestrictionGroups
      security:
        - jwt:
          - read_write
    delete:
      tags:
        - Merchant ID Restriction Groups
      summary: Cancel MID Restriction Group
      description: Cancel a merchant id restriction group.
      operationId: deleteMerchantIdRestrictionGroups
      security:
        - jwt:
          - read_write
  /v1/merchantIdRestrictionGroups/{id}/DeltaUpdate:
    put:
      tags:
        - Merchant ID Restriction Groups
      summary: Update MID Restriction Group
      operationId: put-merchandidrestrictiongroups-deltaupdate
      description: Update the list of Merchant Ids for a MID Restriction Group.
      security:
        - jwt:
          - read_write
  /v1/merchantIdRestrictionGroups/{id}/PresenceCheck:
    put:
      tags:
        - Merchant ID Restriction Groups
      summary: Check the presence of merchants IDs list for a restriction group
      operationId: put-midrestrictiongroups
      description: Check if Merchant IDs list for a restriction group.
      security:
        - jwt:
          - read_only
          - read_write
  /v1/payins:
    get:
      tags:
        - Payins
      summary: Search Payins
      description: Get payins that match search criteria.
      operationId: getPayins
      security:
        - jwt: []
    post:
      tags:
        - Payins
      summary: Create Payin
      description: Create a new payin.
      operationId: postPayin
      security:
        - jwt: []
  /v1/payins/{payinId}:
    get:
      tags:
        - Payins
      summary: Get Payin
      description: Retrieve a payin by its id.
      operationId: getPayin
      security:
        - jwt: []
    delete:
      tags:
        - Payins
      summary: Delete Payin
      description: | 
        Cancels a Payin. This endpoint is only available for the [Check cashing](/guide/cheques/introduction.html) feature, prior to the check reception at the treatment center.
      operationId: deletePayin
      security:
        - jwt: []
  /v1/payinrefunds:
    get:
      tags:
        - Payin Refunds
      summary: Search Payin Refunds
      description: | 
        Search for payin refunds. These can relate to [Acquiring](/guide/acquiring/legacy-v1.html#refunds) or [SEPA recalls](/guide/transfers/sepa-recalls.html).
      operationId: getPayinrefunds
      security:
        - jwt: []
  /v1/payinrefunds/{id}:
    get:
      tags:
        - Payin Refunds
      summary: Get Payin Refund
      description: Get a payin refund.
      operationId: getPayinrefund
      security:
        - jwt: []
  /v1/payouts:
    get:
      tags:
        - Payouts
      summary: Search Payouts
      description: |
        Retrieve Payouts that match search criteria. The request must contain at least one of the following inputs: `userId`, `walletId`.
      operationId: getPayouts
      security:
        - jwt: []
    post:
      tags:
        - Payouts
      summary: Create Payout
      description: | 
        Create a new payout.

        This endpoint requires per-operation [SCA](/guide/strong-customer-authentication/introduction.html).
      operationId: postPayout
      security:
        - jwt: []
  /v1/payouts/{payoutId}:
    get:
      tags:
        - Payouts
      summary: Get Payout
      description: Retrieve a given Payout.
      operationId: getPayout
      security:
        - jwt: []
    delete:
      tags:
        - Payouts
      summary: Cancel Payout
      description: |
        Change payout status to `CANCELED`. A `VALIDATED` payout can't be canceled.
      operationId: deletePayout
      security:
        - jwt: []
  /v1/payoutRefunds:
    post:
      tags:
        - Payout Refunds
      summary: Create Payout Refund
      description: |
        Create a Payout Refund. 
        As of today, this feature is only available for [emitting SCTE Inst Recalls](/guide/transfers/sepa-recalls.html#emitting-scte-inst-recalls).
        Otherwise, you need to [open a ticket](https://mywebsite.zendesk.com/hc/en-us/articles/4403978479634-How-to-create-a-Zendesk-ticket) to request payout recalls.
      operationId: postPayoutRefund
  /v1/payoutRefunds/{payoutRefundId}:
    get:
      tags:
        - Payout Refunds
      summary: Get Payout Refund
      description: |
        Retrieve a given Payout Refund with its `id`.
      operationId: getPayoutRefund 
  /v1/recallRs:
    get:
      tags:
        - Recalls
      summary: Get Recalls or RRO
      description: Retrieve recalls or RROs
      operationId: getRecallRs
      security:
        - jwt: []
  /v1/recallRs/{recallId}:
    get:
      tags:
        - Recalls
      summary: Get Recall or RRO
      description: Retrieve a given recall or RRO.
      operationId: getRecallR
      security:
        - jwt: []
  /v1/recallRs/{recallId}/response:
    put:
      tags:
        - Recalls
      summary: Respond to Recall or RRO
      description: Respond to a Recall or a RRO.
      operationId: putRecallR
      security:
        - jwt: []
  /v1/recall-sct-inst/{sctInstId}/{recallId}:
    get:
      tags:
        - Recalls
      summary: Get SCT Inst Recall
      operationId: getRecallSctInst
      description: Retrieve an SCT Inst Recall.
      security:
        - jwt: []
  /v1/recall-sct-inst/{sctInstId}/{recallId}/response:
    put:
      tags:
        - Recalls
      summary: Respond to SCT Inst Recall
      operationId: putRecallSctInst
      description: Provide your decision following an SCT Inst Recall.
      security:
        - jwt: []
  /v1/taxResidences:
    get:
      tags:
        - User Tax Residences
      summary: Search Tax Residences
      operationId: getTaxresidences
      description: Retrieve Tax Residences that match your search conditions.
      security:
        - jwt: []
    post:
      tags:
        - User Tax Residences
      summary: Create Tax Residence 
      operationId: postTaxresidence
      description: |
        Create a new Tax Residence.

        This endpoint requires per-session [SCA](/guide/strong-customer-authentication/introduction.html).
      security:
        - jwt: []
  /v1/taxResidences/{taxResidenceId}:
    get:
      tags:
        - User Tax Residences
      operationId: getTaxresidence
      summary: Get Tax Residence
      description: Retrieve a Tax Residence based on its `id`.
      security:
        - jwt: []
    put:
      tags:
        - User Tax Residences
      summary: Update Tax Residence
      operationId: putTaxresidence
      description: | 
        Modify an existing Tax Residence.

        This endpoint requires per-session [SCA](/guide/strong-customer-authentication/introduction.html).
      security:
        - jwt: []
    delete:
      tags:
        - User Tax Residences
      summary: Delete a residence
      operationId: deleteTaxresidence
      description: Delete a residence that match id
      security:
        - jwt: []
  /v1/transactions:
    get:
      tags:
        - Transactions
      summary: Search Transactions
      description: |
        Retrieve Transactions that match search criteria. The request must contain at least one of the following inputs: `walletId`, `transactionId`, `executionDate`, `valueDate`
      operationId: getTransactions
      security:
        - jwt: []
  /v1/transactions/{transactionId}:
    get:
      tags:
        - Transactions
      summary: Get Transaction
      description: Retrieve a transaction.
      operationId: getTransaction
      security:
        - jwt: []
  /v1/transfers:
    get:
      tags:
        - Transfers
      summary: Search Transfers
      description: |
        Retrieve the list of transfers for at least one of those inputs:
        `walletId`, `beneficiaryWalletId`, `userId`, `beneficiaryUserId`, `transferId`, `transferTag`
      operationId: getTransfers
      security:
        - jwt: []
    post:
      tags:
        - Transfers
      summary: Create Transfer
      description: | 
        Create a new Wallet-to-Wallet transfer.

        This endpoint requires per-session or per-operation [SCA](/guide/strong-customer-authentication/introduction.html) on if the `beneficiaryWalletId` belongs to the current User or not.
      operationId: postTransfers
      security:
        - jwt: []
  /v1/transfers/{transferId}:
    get:
      tags:
        - Transfers
      summary: Get Transfer
      description: Retrieve a transfer using its `id`.
      operationId: getTransfer
      security:
        - jwt: []
    delete:
      tags:
        - Transfers
      summary: Cancel Transfer
      description: |
        Change status of the Transfer to `CANCELED`. 
        
        Only transfers whose stauts is `PENDING` can be canceled.
      operationId: deleteTransfer
      security:
        - jwt: []

  /v1/users:
    get:
      tags:
        - Users
      summary: Search Users
      description: Retrieve Users matching your search criteria.
      operationId: getUsers
      security:
        - jwt:
          - read_only
    post:
      tags:
        - Users
      summary: Create User
      description: | 
        You may read [the dedicated documentation for this feature](/guide/users/introduction.html#creation)
      operationId: postUsers
      security:
        - jwt:
          - legal
          - admin
  /v1/users/{userId}:
    get:
      tags:
        - Users
      summary: Get User
      description: Retrieve user's information for given user's `id`.
      operationId: getUser
      security:
        - jwt:
          - read_only
    put:
      tags:
        - Users
      summary: Update User
      description: | 
        Update information regarding the User.

        This endpoint may require per-operation [SCA](/guide/strong-customer-authentication/introduction.html).
      operationId: putUser
      security:
        - jwt:
          - read_write
    delete:
      tags:
        - Users
      summary: Disable User
      description: | 
        Update the user Status to `CANCELED`. See the [Deletion](/guide/users/modifications.html#deletion) article for more information.
      operationId: deleteUser
      security:
        - jwt:
          - read_write
          - admin
  /v1/users/{userId}/Kycreview:
    put:
      tags:
        - User KYC Review
      summary: Request KYC Review
      operationId: putKycreview
      description: |
        Request a KYC review for a given user and its children to Mywebsite. Learn more in the [KYC Request](/guide/user-verification/kyc-request.html) article.
      security:
        - jwt:
          - read_write
  /v1/users/{userId}/kycliveness:
    post:
      tags:
        - Verification Solutions (KYC)
      description: | 
        Start the Live Verficiation process, whether it is KYC Liveness or Certified Video. You may read [the dedicated documentation for this feature](/guide/user-verification/live-verification.html).
      operationId: postKycliveness
      summary: Initiate Live Verification
      security:
        - jwt:
          - read_write
          - admin
    put:
      tags:
        - Verification Solutions (KYC)
      summary: Retrieve and Upload Live Verification Result
      description: | 
        Retrieve the live verification results, and make them available to Mywebsite.
        You may read [the dedicated documentation for this feature](/guide/user-verification/live-verification.html)
      operationId: put-kyc-liveness
      security:
        - jwt:
          - read_write
          - admin
  /v1/users/{userId}/qes:
    post:
      tags:
        - Verification Solutions (KYC)
      summary: Initiate QES Verification
      description: |
        Start the qualified electronic signature (QES) verification. 
      operationId: postKycqes
      security:
        - jwt:
          - read_write
          - admin
  /v1/users/{userId}/videoconference:
    post:
      tags: 
        - Verification Solutions (KYC)
      summary: Initiate Video Conference Verification
      description: |
        Start the [Video conference verification](/guide/user-verification/videoconf.html) process.
      operationId: postKycVconf
  /v1/virtualibans:
    get:
      tags:
        - Virtual IBANs
      summary: Search Virtual IBANs
      description: Retrieve virtual IBANs that match search criteria.
      operationId: getvirtualibans
      security:
        - jwt: []
    post:
      tags:
        - Virtual IBANs
      summary: Create Virtual IBAN
      description: Create a new virtual IBAN associated with a given Wallet.
      operationId: postVirtualIban
      security:
        - jwt: []
  /v1/virtualibans/{virtualIbanId}:
    get:
      tags:
        - Virtual IBANs
      summary: Get Virtual IBAN
      description: Retrieve a Virtual IBAN based on its `id`.
      operationId: getvirtualiban
      security:
        - jwt: []
    put:
      tags:
        - Virtual IBANs
      summary: Update Virtual IBAN
      description: Update a Virtual IBAN's information.
      operationId: putVirtualIban
      security:
        - jwt: []
  /v1/wallets:
    get:
      tags:
        - Wallets
      summary: Search Wallets
      description: |
        Retrieve Wallets that match your search conditions. The request must specify at least one of those fields: `walletId`, `eventAlias`, `userId`, `walletTypeId`.
      operationId: getWallets
      security:
        - jwt:
          - read_only
    post:
      tags:
        - Wallets
      summary: Create Wallet
      description: | 
        Create a new Wallet. This endpoint requires per-session [SCA](/guide/strong-customer-authentication/introduction.html).
      operationId: postWallets
      security:
        - jwt:
          - read_write
  /v1/wallets/{walletId}:
    get:
      tags:
        - Wallets
      summary: Get Wallet
      description: Retrieve a Wallet based on its `id`.
      operationId: getWallet
      security:
        - jwt:
          - read_only
    put:
      tags:
        - Wallets
      summary: Update Wallet
      description: Modifiy a Wallet information
      operationId: putWallet
      security:
        - jwt:
          - read_write
    delete:
      tags:
        - Wallets
      summary: Delete Wallet
      description: Change the status of the Wallet to `CANCELED`. This action is irreversible.
      operationId: deleteWallet
      security:
        - jwt:
          - read_write
  /simulation/payout-sddr:
    post:
      summary: Simulate SDDR Core
      operationId: SimulateSDDR
      description: Simulate a received SEPA Direct Debit into one of your Wallet in Sandbox.
      tags:
        - Payouts
      security:
        - jwt: 
          - admin
          # verified scope
  /simulation/sct-inst/payin:
    post:
      tags:
        - Payins
      summary: Simulate SCTR Inst
      operationId: simulateSctInstReception
      description: Simulate the reception of an instantaneous SEPA Credit Transfer into one of your Wallet in Sandbox.
      security:
        - jwt: 
          - admin
          # verified scope
  /simulation/sct-inst/recall:
    post:
      tags:
        - Recalls
      summary: Simulate SCT Inst recall
      description: Simulate a recall for an instantaneous SEPA Credit Transfer.
      operationId: simulateSctInstRecall
      security:
        - jwt: 
          - admin
          # verified scope
  /simulation/acquiring/payin:
    post:
      summary: Simulate Acquiring Payin
      description: Simulate operations resulting from the card acquisition feature.
      operationId: SimulateAcquiringPayin
      tags:
        - Acquiring (Simulation)
      security:
        - jwt: 
          - admin
          # verified scope
  /simulation/operations:
    post:
      summary: Simulate Operations
      description: | 
        Create fake operations for a given Wallet. This may prove useful to test [Account Statements](/guide/wallets/account-statements.html) for instance.
      operationId: simulateOperations
      tags:
        - Operations
      security:
        - jwt:
          - admin
          # verified scope
  /simulation/cardtransactions:
    post:
      tags:
        - Card Transactions
      summary: Simulate Card Transactions
      description: Simulate Card Transactions in Sandbox environment
      operationId: simulateCardTransactions
      security:
        - jwt: 
          - admin
          # verified scope
  /v1/mdc/rulesets:
    get:
      tags:
      - Card Rulesets (MDC)
      operationId: get-rulesets
      summary: Get Rulesets
      description: Retrieve all rulesets.
      security:
        - jwt: []
    post:
      tags:
      - Card Rulesets (MDC)
      operationId: create-ruleset
      summary: Create Ruleset
      description: Create a Ruleset.
      security:
        - jwt: []
  /v1/mdc/rulesets/{rulesetId}:
    get:
      tags:
      - Card Rulesets (MDC)
      operationId: get-ruleset
      summary: Get Ruleset
      description: Retrieve a Ruleset with its `id`.
      security:
        - jwt: []
    put:
      tags:
      - Card Rulesets (MDC)
      operationId: put-ruleset
      summary: Update Ruleset
      description: Modify a Ruleset.
      security:
        - jwt: []
    delete:
      tags:
      - Card Rulesets (MDC)
      summary: Disable Ruleset
      description: Disable a Ruleset.
      operationId: disable-ruleset
      security:
        - jwt: []
  /v1/mdc/{cardId}/rulesets:
    get:
      tags:
      - Card Rulesets (MDC)
      operationId: get-ruleset-from-card
      summary: Retrieve Card Rulesets
      description: Get all rulesets assigned to a given card.
      security:
        - jwt: []
    post:
      tags:
      - Card Rulesets (MDC)
      summary: Assign Ruleset
      description: Assign rulesets to a given card.
      operationId: attach-ruleset-to-card
      security:
        - jwt: []
  /v1/mdc/{cardId}/ruleset/{rulesetId}/factsBalance:
    get:
      tags:
        - Card Rulesets (MDC)
      summary: Retrieve Ruleset virtual balance
      description: Retrieve a ruleset virtual balance.
      operationId: getFactsBalance
      security:
        - jwt: []
  /v1/cardDigitalizations:
    get:
      tags:
        - Cards Digitalization
      summary: Search Card Digitalizations
      description: Search for card digitalizations.
      operationId: readcardDigitalizations
      deprecated: true
      security:
        - jwt: []
  /v1/cardDigitalizations/{id}:
    get:
      tags:
        - Cards Digitalization
      summary: Get Card Digitalization
      description: Retrieve a Card Digitalization based on its `id`.
      operationId: cardDigitalizationsId
      deprecated: true
      security:
        - jwt: []
    put:
      tags:
        - Cards Digitalization
      summary: Update Payment Token Status
      description: | 
        Update the status of a payment Token

        This endpoint requires per-operation [SCA](/guide/strong-customer-authentication/introduction.html).
      operationId: putcardDigitalizationsId
      deprecated: true
      security:
        - jwt: []
    delete:
      tags:
        - Cards Digitalization
      summary: Delete Payment Token
      description: Delete a payment Token
      operationId: deletecardDigitalizationsId
      deprecated: true
      security:
        - jwt: []
  /core-connect/scheduledPayment:
    post:
      tags:
        - Scheduled Payments
      summary: Create Scheduled Payment
      description: | 
        Schedule a Payout or a Wallet-to-Wallet transfer for a future date.

        This endpoint requires per-operation [SCA](/guide/strong-customer-authentication/introduction.html).
      operationId: postScheduledPayment
      security:
        - jwt:
          - read_write
    get:
      tags:
        - Scheduled Payments
      summary: Get Scheduled Payment
      description: Retrieve Scheduled Payment orders based on the corresponding `userId` and/or `walletId`
      operationId: getScheduledPayment
      security:
        - jwt:
          - read_only
          - read_write
  /core-connect/scheduledPayment/{scheduledPaymentId}:
    delete:
      tags:
        - Scheduled Payments
      summary: Delete Scheduled Payment
      description: Cancel a Scheduled Payment order
      operationId: deleteScheduledPayment
      security:
        - jwt:
          - read_write
  /core-connect/scheduledPayment/{scheduledPaymentId}/payments:
    get:
      tags:
        - Scheduled Payments
      summary: Get Scheduled Payment Operations
      description: Retrieve the list of executed payments for a given Scheduled Payment order
      operationId: getScheduledPaymentOperations
      security:
        - jwt:
          - read_only
          - read_write
  /v1/topups/cards/authorizations:
    post:
      summary: Create Authorization
      description: | 
        Create an authorization to make a card topup payin within 7 days. The card must be [tokenized](/guide/acquiring/card-tokenization.html) first.
      operationId: postAcqAuth
      tags:
        - Acquiring (Card Topups)
      security:
        - jwt:
            - read_write
  /v1/topups/cards/authorizations/{authorizationUuid}:
    get:
      summary: Get Authorization
      description: Retrieve an authorization from the system.
      operationId: getAcqAuth
      tags:
        - Acquiring (Card Topups)
      security:
        - jwt:
            - read_write
            - read_only
    delete:
      summary: Delete Authorization
      description: Delete an authorization from the system
      operationId: deleteAcqAuth
      tags:
        - Acquiring (Card Topups)
      security:
        - jwt:
            - read_write
  /v1/topups/cards/authorizations/{authorizationUuid}/payins:
    post:
      summary: Create Payin from Authorization
      description: Create a payin from an authorization. The amount must be ≤ to the authorization amount. [Learn more](/guide/acquiring/preauthorized.html#advanced-capture).
      operationId: postAcqAuthPayin
      tags:
        - Acquiring (Card Topups)
      security:
        - jwt:
            - read_write
    get:
      summary: Get Authorization Payins
      description: List payins created from a given authorization.
      operationId: getAcqAuthPayins
      tags:
        - Acquiring (Card Topups)
      security:
        - jwt:
            - read_write
            - read_only

  /simulation/topups/cards/notification/authorizations:
    post:
      summary: Simulate an HiPay authorization notification
      description: |
        Mocks an HiPay authorization notification provided the minimal set of
        parameters to generate a refund notification.
      operationId: acquiringv2-topup-cards-simulation-notification-autorization
      tags:
        - Acquiring (Simulation)
      security:
        - jwt:
            - admin
  /simulation/topups/cards/notification/payins:
    post:
      summary: Simulate an HiPay payin notification
      description: |
        Mocks an HiPay payin notification providing the minimal set of
        parameters to generate a payin notification.
      operationId: acquiringv2-topup-cards-simulation-notification-payins
      tags:
        - Acquiring (Simulation)
      security:
        - jwt:
            - admin
  /simulation/topups/cards/notification/refunds:
    post:
      summary: Simulate an HiPay refund notification
      description: |
        Mocks an HiPay refund notification providing the minimal set of
        parameters to generate a refund notification.
      operationId: acquiringv2-topup-cards-simulation-notification-refunds
      tags:
        - Acquiring (Simulation)
      security:
        - jwt:
            - admin
  /simulation/topups/cards/notification/chargebacks:
    post:
      summary: Simulate an HiPay chargeback notification
      description: |
        Mocks an HiPay chargeback notification providing the minimal set of
        parameters to generate a chargeback notification.
      operationId: acquiringv2-topup-cards-simulation-notification-chargebacks
      tags:
        - Acquiring (Simulation)
      security:
        - jwt:
            - admin
  /v1/topups/cards/refunds/{refundUuid}:
    get:
      summary: Get Refund
      description: Retrieve a card acquring refund from the system.
      operationId: acquiringv2-topup-cards-refunds-get
      tags:
        - Acquiring (Card Topups)
      security:
        - jwt:
            - read_write
            - read_only
  /v1/topups/cards/refunds:
    post:
      summary: Create Refund
      description: Create a new card topup refund.
      operationId: acquiringv2-topup-cards-refunds-post
      tags:
        - Acquiring (Card Topups)
      security:
        - jwt:
            - read_write
  /v1/topups/cards/chargebacks/{chargebackUuid}:
    get:
      summary: Get Chargeback
      description: Retrieve a card acquiring a chargeback from the system.
      operationId: acquiringv2-topup-cards-chargebacks-get
      tags:
        - Acquiring (Card Topups)
      security:
        - jwt:
            - read_write
            - read_only
  /v1/topups/cards/users/{userId}/topupCards:
    post:
      summary: Create Topup Card
      description: |
        Create a new topup card. The card must have been previously tokenized.
      operationId: postTopupCard
      tags:
        - Acquiring (Card Topups)
      security:
        - jwt:
            - read_write
    get:
      summary: Search Topup Cards
      description: Get topup cards.
      operationId: getTopupCards
      tags:
        - Acquiring (Card Topups)
      security:
        - jwt:
            - read_write
            - read_only
  /v1/topups/cards/users/{userId}/topupCards/{topupCardId}:
    get:
      summary: Get Topup Card
      description: Retrieve the details of a Topup Card.
      operationId: getTopupCard
      tags:
        - Acquiring (Card Topups)
      security:
        - jwt:
            - read_write
            - read_only
    delete:
      summary: Cancel Topup Card
      description: Change topup card status to CANCELED.
      operationId: deleteTopupCard
      tags:
        - Acquiring (Card Topups)
      security:
        - jwt:
            - read_write
components:
  securitySchemes:
    jwt:
      type: oauth2
      description: | 
        The Mywebsite API is secured by a JWT provided by Mywebsite, with OAuth2 client credentials flow.
        The token can be used in the `Authorization` header as `Bearer <token>`.
      flows:
        clientCredentials:
          tokenUrl: https://baseUrl.co/oauth/token
          refreshUrl: https://baseUrl.co/oauth/token
          scopes:
            read_only: Gives access to all endpoints (expect keys, legal, admin) in GET (End user oriented)
            read_write: Gives access to all endpoints (expect keys, legal, admin) in PUT|POST|DELETE (End user oriented)
            read_all: Gives access to all endpoints in GET (Use carefully)
            admin: Gives access to API configuration related endpoints
            legal: Gives access to KYC, users and users documents related endpoints
            keys: Gives access to encryption keys management related endpoints
            support_user_management: Gives access to support users related endpoints
        # password:
        #   tokenUrl: https://baseUrl.co/oauth/token
        #   refreshUrl: https://baseUrl.co/oauth/token
        #   scopes:
            # read_only: Gives access to all endpoints (expect keys, legal, admin) in GET (End user oriented)
            # read_write: Gives access to all endpoints (expect keys, legal, admin) in PUT|POST|DELETE (End user oriented)
            # read_all: Gives access to all endpoints in GET (Use carefully)
            # admin: Gives access to API configuration related endpoints
            # legal: Gives access to KYC, users and users documents related endpoints
            # keys: Gives access to encryption keys management related endpoints
            # support_user_management: Gives access to support users related endpoints
        # implicit:
        #   authorizationUrl: https://baseUrl.co/oauth/token
        #   refreshUrl: https://baseUrl.co/oauth/token
        #   scopes:
        #     read_only: Gives access to all endpoints (expect keys, legal, admin) in GET (End user oriented)
        #     read_write: Gives access to all endpoints (expect keys, legal, admin) in PUT|POST|DELETE (End user oriented)
        #     read_all: Gives access to all endpoints in GET (Use carefully)
        #     admin: Gives access to API configuration related endpoints
        #     legal: Gives access to KYC, users and users documents related endpoints
        #     keys: Gives access to encryption keys management related endpoints
        #     support_user_management: Gives access to support users related endpoints
tags:
  - name: Account Details
    description: |
      The Account Details object corresponds to the bank details of the Wallet, with all the relevant information such as the IBAN and the owner's identity.

      _Related articles: [Account Details](/guide/wallets/account-details.html) | [Wallets](/guide/wallets/introduction.html)_
  - name: Account Statements
    description: |
      The Account Statement object synthesizes all operations affecting the [Balance](/guide/overview/glossary#balance) of a [Wallet](/guide/wallets/introduction) for a given month. It also provides the Balance at the start and end of that month, the sum of debits, and the sum of credits. 

      _Related articles: [Account Statements](/guide/wallets/account-statements.html) | [Wallets](/guide/wallets/introduction.html)_
  - name: Acquiring (Card Topups)
    description: | 
      Card Acquiring consists of capturing funds from a third-party card to credit a Mywebsite [Wallet](/guide/wallets/introduction). 

      _Related articles: [Card Acquiring](/guide/acquiring/introduction.html)_
  - name: Acquiring (Simulation)
    description: | 
      Dedicated set of endpoints so emulate card acquiring payins, and the related notifications.

      _Related articles: [Card Acquiring](/guide/acquiring/introduction.html) | [Emulation](/guide/acquiring/faking-operations.html)_
  - name: API Templates
    description: |
      Mywebsite offers a series of templates to customize emails and files, that you can manage via dedicated endpoints. Please bear in mind templates are base64-encoded files.

      _Related articles: [Templates](/guide/api-basics/templates.html) | [Email Templates](/guide/api-basics/emails.html#templates)_
  - name: Authentication
    description: |
      Mywebsite leverages the [OAuth2 framework](https://en.wikipedia.org/wiki/OAuth) and [JSON Web Token (JWT)](/guide/overview/glossary#json-web-token-jwt) which allows for a wide range of authentication flows.
      
      The obtained Bearer access token can then be used in the Authorization headers to authenticate your calls to the Mywebsite API.

      _Related articles: [Authentication](/guide/api-basics/authentication.html)_
  - name: Balances
    description: |
      The Balance object provides the amount available on a given Wallet. Read more about the different kind of balances in the [Balance definition](/guide/overview/glossary.html#balance) of the Glossary.

      _Related articles: [Balances](/guide/wallets/balances.html) | [Wallets](/guide/wallets/introduction.html)_
  - name: Beneficiaries
    description: |
      The Beneficiary object represents a bank account that is outside of your Mywebsite ecosystem (as opposed to [Wallets](/guide/dashboard/wallets#wallets)). 
      
      They are therefore the target of payouts (SEPA Direct Debit and SEPA Credit Transfers), and are necessarily attached to a User.

      _Related articles: [Beneficiaries](/guide/transfers/beneficiaries.html) | [SEPA Transfers](/guide/transfers/introduction.html)_
  - name: Businesses
    description: |
      Mywebsite provides dedicated endpoints to help you check information regarding a legal entity, provided you have its VAT or registration number.

      _Related articles: [Checking for veracity](/guide/users/legal-entity.html#checking-for-veracity) | [Legal Entities](/guide/users/legal-entity.html)_
  - name: Cards
    description: |
      The Card object represents a Physical or Virtual Card issued with Mywebsite services.

      Following your [Card Program](/guide/cards/introduction#card-program) and your agreement with Mywebsite, you can issue, manage, and configure cards with options, restrictions, and limits to best suit your use case.

      _Related articles: [Cards](/guide/cards/introduction.html) | [Creation](/guide/cards/creation.html) | [Modifications](/guide/cards/modification.html) | [Restrictions & limits](/guide/cards/restrictions-limits.html)_
  - name: Cards Bulk Creation
    description: |
      Mywebsite allows you to create cards in bulk with a dedicated set of endpoints.

      _Related articles: [Bulk Creation](/guide/cards/creation.html#bulk-creation) | [Cards](/guide/cards/introduction.html)_
  - name: Cards Digitalization
    description: |
      **Deprecated**
  - name: Card 3DSecure Enrollment (SCA)
    description: |
      When eligible to SCA, most card transactions must be authenticated, hence ensuring the legitimate cardholder is initiating the transaction. 

      For the authentication step to be SCA-compliant, you must enroll the card for out of band authentication.

      _Related articles: [Card enrollment](/guide/strong-customer-authentication/securing-endpoints.html#sca-for-card-transactions) | [SCA](/guide/strong-customer-authentication/introduction.html)_
  - name: Card Rulesets (MDC)
    description: |
      The Ruleset object of the Multi-Criteria Dynamic Card rules engine allows you to authorize or refuse a Card Transaction based on your own set of rules.

      _Related articles: [Multi-Criteria Dynamic Card](/guide/cards/transactions-rules-engine.html)_
  - name: Card Transactions
    description: |
      The Card Transaction object represents a step of a card payment made with a Mywebsite-issued Card (e.g., authorization, settlement, or refund).

      Card Transactions relating to the same payment (or payment attempt) have the same `paymentId` value.

      _Related articles: [Card Transactions](/guide/cards/transactions.html) | [Transactions life cycle](/guide/cards/transactions-lifecycle.html) | [Transaction examples](/guide/cards/transactions-examples.html)_
  - name: Country Restriction Groups
    description: |
      The Country Restriction Group object is a whitelist or blacklist of countries. These lists allow you to specify if a given card should be used in specific countries (or forbidden in some countries).

      _Related articles: [List-based restrictions](/guide/cards/restrictions-limits.html#country-restrictions) | [Cards](/guide/cards/introduction.html)_
  - name: Digitalized Cards
    description: |
      The digitization of a Card is the act of tokenizing an existing Card and store it in a Google Pay, Apple Pay, or Samsung Pay wallet.

      _Related articles: [X-Pay](/guide/cards/x-pay-google-apple.html) | [Cards](/guide/cards/introduction.html)_
  - name: Mandates
    description: |
      The Mandate object represents the formal document allowing a [Legal Entity](/guide/users/legal-entity) to initiate a transfer of funds from somebody else's account, to theirs. 

      The transfer is made using [SEPA Direct Debit (SDDE)](direct-debit#emitted-direct-debits-sdde) and can be used to receive one-time or recurring payments.

      _Related articles: [Mandates](/guide/transfers/mandates.html) | [SEPA Direct Debit](/guide/transfers/direct-debit.html#emitted-direct-debits-sdde)_
  # - name: Mass Payouts
  #   description: |
  #     Related articles: [Mass Payout](/guide/transfers/credit-transfer.html#mass-scte-mass-payout) | [SEPA Transfers](/guide/transfers/introduction.html)
  - name: MCC Restriction Groups
    description: |
      The MMC Restriction Group object represents a list-based restriction allowing you to limit the usage of the card to specific categories of merchants.

      _Related articles: [List-based restrictions](/guide/cards/restrictions-limits.html#mcc-restrictions) | [Cards](/guide/cards/introduction.html)_
  - name: Merchant ID Restriction Groups
    description: |
      The MID Restriction Group object is a list-based restriction allowing you to limit the usage of the card to specific merchants.

      _Related articles: [List-based restrictions](/guide/cards/modification.html#list-based-restrictions) | [Cards](/guide/cards/introduction.html)_
  - name: Merchant ID Metadata
    description: |
      In some cases, the [Merchant Id (MID)](/guide/overview/glossary#merchant-identification-number-mid) may not be up-to-date or the given information not enough for you to act on it. 
      
      Mywebsite offers endpoints to add metadata to MIDs, hence allowing you to add human-readable information as you see fit.

      _Related articles: [MID Metadata](/guide/cards/restrictions-limits.html#mid-restrictions) | [Cards](/guide/cards/introduction.html)_
  - name: Operations
    description: |
      The Operation object represents for banking operations originating from or targeting a [Wallet](/guide/wallets/introduction) (i.e., Card Transactions, Payins, Payouts, and Transfers) and their refunds. 
      
      Each Operation summarizes the initial transaction with read-only information such as the nature, status, amount, origin, and destination.

      _Related articles: [Operations](/guide/operations/introduction.html)_
  - name: Payins
    description: |
      The Payin object represents a movement of fund from an external account to a Mywebsite Wallet, and thus regardless of the means of payment used (SEPA Transfers, Checks, Card Top-ups).

      Related articles: [SCTR](/guide/transfers/credit-transfer.html#received-credit-transfers-sctr) | [SDDE](/guide/transfers/direct-debit.html#emitted-direct-debits-sdde) | [Card top-up](/guide/acquiring/introduction.html) | [Check](/guide/cheques/introduction.html)
  - name: Payin Refunds
    description: |
      The Payin Refund object represents the reimbursement of a Payin.

      Related articles: [SCTR Recalls](/guide/transfers/sepa-recalls.html#receiving-sctr-recalls)
  - name: Payouts
    description: |
      The Payout object represents a movement of funds from an external account into a Mywebsite Wallet, specifically the ones made through SEPA Transfers.

      _Related articles: [Card Transactions](/guide/cards/transactions.html) | [SCTE](/guide/transfers/credit-transfer.html#emitted-credit-transfers-scte) | [SDDR](/guide/transfers/direct-debit.html#received-direct-debits-sddr)_
  - name: Payout Refunds
    description: |
      The Payout Refund object represents the reimbursement of a Payout. 

      _Related articles: [SCTE Inst Recalls](/guide/transfers/sepa-recalls.html#emitting-scte-inst-recalls)_
  - name: Recalls
    description: |
      Recalls occur when the originator of a [SEPA Credit Transfer (SCT)](/guide/overview/glossary#sepa-credit-transfer-sct) ask to reverse the transfer.

      Mywebsite offers endpoints to generate these requests or answers them depending on the type of the initial transfer.

      _Related articles: [Recalls & RROs](/guide/transfers/sepa-recalls.html)_
  - name: Scheduled Payments
    description: |
      Scheduled Payment orders allow you to plan a payment execution in the future, whether it is a unique operation or recurring ones. 
      
      Scheduled Payments can be used for both [Payouts (SCTE)](/guide/transfers/credit-transfer#emitted-credit-transfers-scte) and [Wallet-to-Wallet Transfers](/guide/wallets/wallet-to-wallet#wallet-to-wallet-transfers).
      
      _Related articles: [Scheduled Payments](/guide/transfers/scheduled-payments.html) | [SCTE](/guide/transfers/credit-transfer.html#emitted-credit-transfers-scte) | [Wallet-to-Wallet](/guide/transfers/wallet-to-wallet.html)_
  - name: SCA
    description: |
      The SCA Wallet object represents the secure enclave locally present on a device, which contains the private key for Strong Customer Authentication.

      _Related articles: [SCA Wallets](/guide/strong-customer-authentication/introduction.html#sca-wallet-object) | [SCA](/guide/strong-customer-authentication/introduction.html)_
  - name: SCA External Operations
    description: |
      The External Operation object represents any end user sensitive action that you need to declare when eligible to Strong Customer Authentication.

      When applugin SCA outside of Mywebsite services, you're legally required to declare these actions to Mywebsite. Mywebsite then uses these declarations for reporting to the regulator.

      _Related articles: [SCA External Operations](/guide/strong-customer-authentication/securing-endpoints.html#declaring-sca-external-operations) | [SCA](/guide/strong-customer-authentication/introduction.html)_
  - name: SCA Proof Simulation
    description: |
      You can generate fake SCA proofs in Sandbox for testing your strong customer authentication integration. 

      _Related articles: [SCA Proof Simulation](/guide/strong-customer-authentication/faking-operations.html#simulate-sca-proof) | [SCA](/guide/strong-customer-authentication/introduction.html)_
  - name: Support Users
    description: |
      Support Users represent your employees, with specific access to your back office and/or the [Dashboard](/guide/dashboard/introduction) to manage your end users.

      Contrary to end users, Support Users can't have [Wallets](/guide/wallets/introduction), [Cards](/guide/cards/introduction), and cannot initiate of funds related operations.

      _Related articles: [Support Users](/guide/users/support.html) | [Dashboard Users](/guide/dashboard/dashboard-users.html)_
  - name: Transactions
    description: |
      Transactions are a read-only representation of banking operations on a [Wallet](./introduction).

      If you are using [Mywebsite Connect](/guide/overview/getting-started#mywebsite-api), the [Operations](/guide/operations/introduction) endpoint supersedes this one.

      _Related articles: [Transactions](/guide/wallets/transactions.html) | [Wallets](/guide/wallets/introduction.html)_
  - name: Transfers
    description: |
      The Transfer object represents a movement of funds from one Mywebsite Wallet to another.

      Both Wallets must belong to the same Mywebsite environment in order to perform a Wallet-to-Wallet Transfer (also referred to as peer-to-peer or P2P).

      _Related articles: [Wallet-to-Wallet](/guide/transfers/wallet-to-wallet.html) | [Wallets](/guide/wallets/introduction.html)_
  - name: User Document Pre-review
    description: |
      Dedicated set of endpoints for uploading documents to Mywebsite with a built-in pre-validation process.

      Users upload files through pre-signed forms. 
      These files are stored on dedicated servers while your teams review them. 
      The actual Document objects are created in the Mywebsite API once the files are validated.

      Related articles: [Document Pre-review](/guide/user-verification/documents-prereview.html) | [User verification](/guide/user-verification/introduction.html)
  - name: User Documents
    description: |
      Documents are evidence required by Mywebsite to ensure Users are who they claim to be.

      During the KYC/B review, Mywebsite compares documents to the user’s declarative data. 
      The user is verified if the documents are in order (as well as any other verification requirement).
      
      _Related articles: [Documents](/guide/user-verification/documents.html) | [User verification](/guide/user-verification/introduction.html)_
  - name: User KYC Review
    description: |
      Mywebsite is legally obligated to verify the identity of the users using its services, whether it's you as a company or your end users.

      Once you've provided all the relevant information regarding a user, you may request the KYC Review, so that Mywebsite's team can either validate or refuse the user.

      _Related articles: [KYC Request](/guide/user-verification/kyc-request.html) | [User verification](/guide/user-verification/introduction.html)_
  - name: User Onboarding
    description: |
      Mywebsite provides endpoints for users to create their account themselves. 

      _Related articles: [Onboarding](/guide/users/onboarding.html) | [Users](/guide/users/introduction.html)_
  - name: User Tax Residences
    description: |
      All users (both physical users and legal entities) going through the KYC verification process must declare at least one country of tax residency. 
      
      This is an obligation enforced by the [CRS](/guide/overview/glossary#common-reporting-standard-crs) and [FATCA](/guide/overview/glossary#foreign-account-tax-compliance-act-fatca).

      _Related articles: [Tax residence](/guide/user-verification/tax-residence.html) | [User verification](/guide/user-verification/introduction.html)_
  - name: Users
    description: |
      The User object usually represents your customers, also referred to as end users. They can either be physical users or legal entities.

      _Related articles: [Physical Users](/guide/users/physical.html) | [Legal Entities](/guide/users/legal-entity.html) | [Users](https://docs.mywebsite.com/guide/users/introduction.html)_
  - name:  Verification Solutions (KYC)
    description: |
      Mywebsite relies on several verification solutions to ease the physical user verification process. 
      
      The solutions available to you depend on the type of user and the distribution country.

      _Related articles: [User verification](/guide/user-verification/introduction.html)_
  - name: Virtual IBANs
    description: |
      In addition to the automatically assigned IBAN, Virtual IBANs can be created. Wallets can have as many Virtual IBANs as you see fit, to answer a large variety of use cases.

      _Related articles: [IBAN](/guide/wallets/iban.html) | [Wallets](/guide/wallets/introduction.html)_
  - name: Wallets
    description: |
      The Wallet object is like an account holding funds. They are necessary for any type of transaction in the Mywebsite environment.

      Wallets are usually  attached to your end users, allowing for the setup of their means of payment (cards, transfers, etc.). 
      Mywebsite offers various types of wallets to adapt to multiple use cases and technical architectures while remaining compliant in a highly regulated context.

      _Related articles: [Wallets](/guide/wallets/introduction.html)_
